feat: добавлена возможность получить список популярных фильмов с филь…
Scadouge/java-filmorate pull request #20
Opened 2024-04-30 10:50 UTC by JackPushkin

Популярные фильмы с фильтрацией п жанру и году

2024-04-30 11:37 UTC, Scadouge requested changes

2024-04-30 11:37 UTC, Scadouge commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/DbFilmStorageTest.java
> +        Collection<Film> popularByLikesMaxOne = filmStorage.getPopularByYearAndGenre(1, null, null);
Добавь тестовые запросы с проверками для новых параметров тоже.

2024-05-01 11:37 UTC, JackPushkin commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/DbFilmStorageTest.java
> +        Collection<Film> popularByLikesMaxOne = filmStorage.getPopularByYearAndGenre(1, null, null);
Добавил дополнительный тест для проверки фильтрации по жанру и году

2024-05-01 19:22 UTC, Scadouge approved these changes

2024-05-04 19:17 UTC, ilia-kmrv approved these changes

2024-05-04 19:25 UTC, merged