feat: добавлены рекомендации
Scadouge/java-filmorate pull request #21
Opened 2024-05-02 20:19 UTC by helloWoor1d

2024-05-02 21:06 UTC, Scadouge requested changes

2024-05-02 21:06 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/DbFilmStorage.java
> +                    .add(get(rs.getLong("film_id")));
Запросы в циклах не пройдут проверку у ревьювера.

2024-05-02 21:06 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/recommendations/SlopeOne.java
> +    private static final Map<Film, HashMap<Film, Integer>> freq = new HashMap<>();
Надо пересмотреть применение статического поля.

2024-05-05 10:06 UTC, ilia-kmrv approved these changes
Думаю можно мержить.

2024-05-05 10:16 UTC, Scadouge approved these changes

2024-05-05 10:17 UTC, merged