Add reviews
Scadouge/java-filmorate pull request #22
Opened 2024-05-03 22:46 UTC by ilia-kmrv

Добавлена функциональность "Отзывы" ссылка на #8 .

2024-05-03 23:26 UTC, Scadouge requested changes

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        try {
Нужно ли тут использовать try-catch?

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public Review updateReview(Review review) {
Может вызовем в этом методе reviewStorage.get(review.getId()) чтобы убедится что обновляемые объект существует?

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.deleteReview(reviewService.getReview(id));
Раз мы везде передаем айдишники на сервис, может тогда и здесь получение объекта отзыва лучше перенести туда?

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.addLikeToReview(reviewId, userId);
Надо добавить получение объектов моделей вместо id и передать их на dal уровень
reviewStorage.addLikeToReview(reviewStorage.get(reviewId), userStorage.get(userId));

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.addDislikeToReview(reviewId, userId);
Тоже как и с addLikeToReview

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.deleteLikeOrDislikeFromReview(reviewId, userId);
Тоже как и с addLikeToReview

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return reviewStorage.getAllReviewsByFilmId(filmId, count);
Тоже как и с addLikeToReview

2024-05-03 23:26 UTC, Scadouge commented on src/main/resources/schema.sql
> +    useful INTEGER
Давай тут приведем порядок как в других таблицах

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    // TODO: ReviewController class
TODO комментарии оставлены специально?

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Тут не точно, но мне кажется что метод update не выбрасывает EmptyResultDataAccessException, как это делает queryForObject, так что проверять нахождения объекта здесь и в подобных методах надо сделать на уровне сервиса, как мы это сделали в других местах.

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (EmptyResultDataAccessException e) {
см. комментарии к методу update

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (DataAccessException e) {
см. комментарии к методу update

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (DataAccessException e) {
см. комментарии к методу update

2024-05-03 23:26 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (DataAccessException e) {
см. комментарии к методу update

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Добавление лайка отзыву с id={} от юзера с id={}", id, userId);
Поскольку Андрей тут уже все "выкопал", я докапаюсь до ерунды) Глаз колет, что в логах отличаются формулировки, в некоторых человек - юзер, а в других - пользователь. Может одинаково сделать? Для унификации)

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewStorage.java
> +    // TODO: ReviewStorage interface
Уже видел вопрос про TODO комментарий. На всякий случай обращаю внимание, что тут он тоже есть

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +    // TODO: DbReviewStorage class
Тут тот же коммент)

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +    public static final int DISLIKE_VALUE = -1;
Тут недопонял. Напиши плз, зачем статика в полях? Где ещё, кроме этого класса мы используем эти константы?

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +            params.put("useful", review.getUseful());
Поясни плз, я могу просто тупить. В ТЗ сказано - "При создании отзыва рейтинг равен нулю", то есть при добавлении нового отзыва в БД useful должен быть ноль. Если я передам в теле запроса useful = 17, то в БД что сохранится?

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        // TODO: DbReviewStorage get method
Комментарий

2024-05-04 10:55 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Если я правильно помню, метод update возвращает количество измененных записей. То есть можно написать:
int count = jdbcTemplate.update(.......);
if (count == 0) { throw ..... }
Но это не точно)

2024-05-04 11:05 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +    public static final int DISLIKE_VALUE = -1;
Не должно быть "магических чисел" в коде, такое надо выводить в константы, другой вопрос - если мы не используем их в других классах, надо бы их сделать private, если это действительно так

2024-05-04 11:10 UTC, JackPushkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +    public static final int DISLIKE_VALUE = -1;
Константы не обязаны быть статик

2024-05-04 12:44 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +            throw new ItemNotFoundException(review.getUserId() | review.getFilmId(), e.getMessage());
Нет необходимости, чек есть в сервисе.
Исправил.

2024-05-04 12:44 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        try {
Нет необходимости, удалил.

2024-05-04 12:45 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public Review updateReview(Review review) {
Исправил.

2024-05-04 12:45 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.deleteReview(reviewService.getReview(id));
Переделал, как и в остальных стлучаях.

2024-05-04 12:46 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.addLikeToReview(reviewId, userId);
Здесь и далее, исправил.

2024-05-04 12:48 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Выбрасывает, но чек перенёс в сервис, так что не актуально.
@JackPushkin да, возвращает количество изменённых записей)

2024-05-04 12:48 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Здесь и далее, исправил.

2024-05-04 12:49 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Добавление лайка отзыву с id={} от юзера с id={}", id, userId);
Да, выглядит немного диковато, исправил)

2024-05-04 12:49 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewStorage.java
> +    // TODO: ReviewStorage interface
Вроде всё удалил)

2024-05-04 12:54 UTC, Scadouge commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +        params.put("useful", review.getUseful());
Уже писали про это, надо ли давать возможность выставлять useful при создании?

2024-05-04 12:54 UTC, ilia-kmrv commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/DbReviewStorage.java
> +            params.put("useful", review.getUseful());
Напрямую в ТЗ не сказано, сколько раз пользователь может поставить лайки/дизлайки отзыву, но я так предполагаю, что один раз, поэтому понадобилась дополнительная таблица для хранения рейтингов отзыва. При создании отзыва и передаче любого числа будет или 0, если отзыв новый, или то, что хранится в таблице для данного отзыва, через тело запроса изменить useful не получится.

2024-05-04 13:49 UTC, Scadouge approved these changes

2024-05-04 18:11 UTC, JackPushkin approved these changes

2024-05-04 19:09 UTC, merged